##########################################################################################
# Deploys diff files in a PR to your default scratch org
# 1. brew install python
# 2. brew install pip3
# 3. Create and add a GITHUB_TOKEN environment variable to `.zshrc` (https://github.com/settings/apps)
# 4. Execute python3 ./scripts/python/github/read_and_deploy_pr_files_changed.py
# 5. Provide the github url whose files you want to deploy
##########################################################################################
import requests
import os
import subprocess
import sys
from urllib.parse import urlparse, parse_qs

from dotenv import load_dotenv

load_dotenv()


def get_pr_details(pr_url):
    """
    Extract the owner, repo, and PR number from the PR URL.

    Args:
        pr_url (str): The URL of the GitHub Pull Request.

    Returns:
        tuple: A tuple containing the owner, repo, and PR number.
    """
    parsed_url = urlparse(pr_url)
    path_parts = parsed_url.path.strip("/").split("/")
    owner = path_parts[0]
    repo = path_parts[1]
    pr_number = path_parts[3]
    return owner, repo, pr_number


def get_changed_files(owner, repo, pr_number, token):
    """
    Fetch the list of changed files in a pull request with pagination.

    Args:
        owner (str): The owner of the GitHub repository.
        repo (str): The name of the GitHub repository.
        pr_number (str): The number of the pull request.
        token (str): The GitHub access token.

    Returns:
        list: A list of file names that have changed in the pull request.
    """
    files = []
    page = 1
    per_page = 100  # Adjust the number of items per page to the maximum allowed to reduce the number of API calls
    while True:
        url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}/files?page={page}&per_page={per_page}"
        headers = {"Authorization": f"token {token}"}
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            batch_files = response.json()
            if not batch_files:
                break
            files.extend(
                [
                    file["filename"]
                    for file in batch_files
                    if file.get("status") != "removed"
                ]
            )
            page += 1
        else:
            return None  # Or handle errors appropriately
    return files


def generate_deploy_command(files):
    """
    Generate a single Salesforce deployment command based on file paths.

    Args:
        files (list): A list of file paths.

    Returns:
        str: The generated deployment command.
    """
    metadata_mapping = {
        "/classes/": "ApexClass",
        "/permissionsets/": "PermissionSet",
        "/lwc/": "LightningComponentBundle",
        "/aura/": "AuraDefinitionBundle",
        "/objects/": "CustomObject",
        "/customMetadata/": "CustomMetadata",
    }

    deployment_details = {}
    for file in files:
        if "/gpt-generated/" in file:
            # Skip apex tests generated by GPT
            continue
        if "/typings/" in file:
            # Skip typings files
            continue
        if "/lwc/__tests__/" in file:
            # Skip LWC test files
            continue
        if "/objects/" in file and "/fields/" in file:
            # This is a custom field, deploy the entire object instead
            parts = file.split("/")
            object_index = parts.index("objects") + 1
            object_name = parts[object_index]
            metadata_key = f"CustomObject:{object_name}"
            deployment_details[metadata_key] = True
        elif "CustomLabels.labels-meta.xml" in file:
            # This is the CustomLabels file, deploy all CustomLabels
            metadata_key = "CustomLabel"
            deployment_details[metadata_key] = True
        else:
            for path_segment, metadata_type in metadata_mapping.items():
                if path_segment in file:
                    file_name = file.split("/")[-1].split(".")[0]
                    left_side_content = file.rsplit("/", 1)[
                        0
                    ]  # Get the content to the left of the last "/"
                    if metadata_type == "CustomObject" and not file.endswith(
                        ".object-meta.xml"
                    ):
                        # Skip if it's an inner component of an object unless it's the object definition itself
                        continue
                    if (
                        metadata_type == "LightningComponentBundle"
                        and file_name not in left_side_content.split("/")
                    ):
                        # Skip if this is a non-core file of an LWC
                        continue
                    metadata_key = f"{metadata_type}:{file_name}"
                    deployment_details[metadata_key] = True
                    break

    # Generate the deployment command with all necessary components
    deploy_command = f"sf project deploy start -r -m {' -m '.join(deployment_details)}"
    return deploy_command


def main():
    """
    Main function to deploy diff files in a PR to a Salesforce org.

    This function prompts the user to enter the GitHub Pull Request URL,
    retrieves the changed files in the PR based on this URL, generates a
    deployment command based on the changed files, and executes the command
    against the specified org or the default org if no alias is provided.

    Usage:
        python3 script.py [org-alias]

    Returns:
        None
    """

    # Prompt the user for the GitHub Pull Request URL
    pr_url = (
        sys.argv[1]
        if len(sys.argv) >= 2
        else input("Enter the GitHub Pull Request URL: ")
    )

    # Ensure GITHUB_TOKEN is set in the environment variables
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        print("GITHUB_TOKEN environment variable is not set.")
        sys.exit(1)

    # Get PR details and changed files based on the PR URL
    owner, repo, pr_number = get_pr_details(pr_url)
    changed_files = get_changed_files(owner, repo, pr_number, token)

    if changed_files:
        deploy_command = generate_deploy_command(changed_files)
        print(f"Generated deployment command: \n\n{deploy_command}")
        subprocess.run(deploy_command, shell=True)
    else:
        print(
            "Failed to retrieve changed files. Check the PR URL and the access token."
        )


if __name__ == "__main__":
    main()
